### ISSUE TITLE
TypeError: get_model_complexity_info()

### ISSUE THREAD

**Issue by Zhangyongtao123** [layumi/person-reid-3d#15]
Hello, I met  a problem when I tried to run train_M.py without any modification to the code. As below:
`Using backend: pytorch
ModelE_dense(
  (nng): KNNGraphE()
  (conv): ModuleList(
    (0): Conv2d(6, 64, kernel_size=(1, 1), stride=(1, 1))
    (1): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1))
    (2): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
    (3): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1))
  )
  (conv_s1): ModuleList()
  (conv_s2): ModuleList()
  (bn): ModuleList(
    (0): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (sa): ModuleList(
    (0): PointnetSAModuleMSG(
      (groupers): ModuleList(
        (0): QueryAndGroup()
        (1): QueryAndGroup()
        (2): QueryAndGroup()
      )
      (mlps): ModuleList(
        (0): Sequential(
          (0): Conv2d(67, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): SE(
            (se_reduce): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1))
            (se_expand): Conv2d(1, 32, kernel_size=(1, 1), stride=(1, 1))
            (swish): MemoryEfficientSwish()
          )
          (3): Conv2d(32, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (5): ReLU(inplace=True)
        )
        (1): Sequential(
          (0): Conv2d(67, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): SE(
            (se_reduce): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1))
            (se_expand): Conv2d(1, 32, kernel_size=(1, 1), stride=(1, 1))
            (swish): MemoryEfficientSwish()
          )
          (3): Conv2d(32, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (5): ReLU(inplace=True)
        )
        (2): Sequential(
          (0): Conv2d(67, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): SE(
            (se_reduce): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1))
            (se_expand): Conv2d(1, 32, kernel_size=(1, 1), stride=(1, 1))
            (swish): MemoryEfficientSwish()
          )
          (3): Conv2d(32, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (5): ReLU(inplace=True)
        )
      )
    )
    (1): PointnetSAModuleMSG(
      (groupers): ModuleList(
        (0): QueryAndGroup()
        (1): QueryAndGroup()
        (2): QueryAndGroup()
      )
      (mlps): ModuleList(
        (0): Sequential(
          (0): Conv2d(131, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): SE(
            (se_reduce): Conv2d(64, 2, kernel_size=(1, 1), stride=(1, 1))
            (se_expand): Conv2d(2, 64, kernel_size=(1, 1), stride=(1, 1))
            (swish): MemoryEfficientSwish()
          )
          (3): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (4): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (5): ReLU(inplace=True)
        )
        (1): Sequential(
          (0): Conv2d(131, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): SE(
            (se_reduce): Conv2d(64, 2, kernel_size=(1, 1), stride=(1, 1))
            (se_expand): Conv2d(2, 64, kernel_size=(1, 1), stride=(1, 1))
            (swish): MemoryEfficientSwish()
          )
          (3): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (4): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (5): ReLU(inplace=True)
        )
        (2): Sequential(
          (0): Conv2d(131, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): SE(
            (se_reduce): Conv2d(64, 2, kernel_size=(1, 1), stride=(1, 1))
            (se_expand): Conv2d(2, 64, kernel_size=(1, 1), stride=(1, 1))
            (swish): MemoryEfficientSwish()
          )
          (3): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (4): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (5): ReLU(inplace=True)
        )
      )
    )
    (2): PointnetSAModuleMSG(
      (groupers): ModuleList(
        (0): QueryAndGroup()
        (1): QueryAndGroup()
        (2): QueryAndGroup()
      )
      (mlps): ModuleList(
        (0): Sequential(
          (0): Conv2d(259, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): SE(
            (se_reduce): Conv2d(128, 5, kernel_size=(1, 1), stride=(1, 1))
            (se_expand): Conv2d(5, 128, kernel_size=(1, 1), stride=(1, 1))
            (swish): MemoryEfficientSwish()
          )
          (3): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (5): ReLU(inplace=True)
        )
        (1): Sequential(
          (0): Conv2d(259, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): SE(
            (se_reduce): Conv2d(128, 5, kernel_size=(1, 1), stride=(1, 1))
            (se_expand): Conv2d(5, 128, kernel_size=(1, 1), stride=(1, 1))
            (swish): MemoryEfficientSwish()
          )
          (3): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (5): ReLU(inplace=True)
        )
        (2): Sequential(
          (0): Conv2d(259, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): SE(
            (se_reduce): Conv2d(128, 5, kernel_size=(1, 1), stride=(1, 1))
            (se_expand): Conv2d(5, 128, kernel_size=(1, 1), stride=(1, 1))
            (swish): MemoryEfficientSwish()
          )
          (3): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (5): ReLU(inplace=True)
        )
      )
    )
    (3): PointnetSAModuleMSG(
      (groupers): ModuleList(
        (0): QueryAndGroup()
        (1): QueryAndGroup()
        (2): QueryAndGroup()
      )
      (mlps): ModuleList(
        (0): Sequential(
          (0): Conv2d(515, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): SE(
            (se_reduce): Conv2d(256, 10, kernel_size=(1, 1), stride=(1, 1))
            (se_expand): Conv2d(10, 256, kernel_size=(1, 1), stride=(1, 1))
            (swish): MemoryEfficientSwish()
          )
          (3): Conv2d(256, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (4): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (5): ReLU(inplace=True)
        )
        (1): Sequential(
          (0): Conv2d(515, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): SE(
            (se_reduce): Conv2d(256, 10, kernel_size=(1, 1), stride=(1, 1))
            (se_expand): Conv2d(10, 256, kernel_size=(1, 1), stride=(1, 1))
            (swish): MemoryEfficientSwish()
          )
          (3): Conv2d(256, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (4): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (5): ReLU(inplace=True)
        )
        (2): Sequential(
          (0): Conv2d(515, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): SE(
            (se_reduce): Conv2d(256, 10, kernel_size=(1, 1), stride=(1, 1))
            (se_expand): Conv2d(10, 256, kernel_size=(1, 1), stride=(1, 1))
            (swish): MemoryEfficientSwish()
          )
          (3): Conv2d(256, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (4): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (5): ReLU(inplace=True)
        )
      )
    )
  )
  (embs): ModuleList(
    (0): Linear(in_features=1024, out_features=512, bias=False)
  )
  (bn_embs): ModuleList(
    (0): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (dropouts): ModuleList(
    (0): Dropout(p=0.7, inplace=True)
  )
  (partpool): AdaptiveAvgPool1d(output_size=1)
  (proj_output): Linear(in_features=512, out_features=751, bias=True)
)
torch.Size([1, 4096, 6])
Traceback (most recent call last):
  File "/home/uisee/anaconda3/envs/OG/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/uisee/anaconda3/envs/OG/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/uisee/.vscode-server/extensions/ms-python.python-2021.10.1365161279/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/uisee/.vscode-server/extensions/ms-python.python-2021.10.1365161279/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/uisee/.vscode-server/extensions/ms-python.python-2021.10.1365161279/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/uisee/anaconda3/envs/OG/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/uisee/anaconda3/envs/OG/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/uisee/anaconda3/envs/OG/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/uisee/yongtao/proj/person-reid-3d/train_M.py", line 362, in <module>
    macs, params = get_model_complexity_info(model.cuda(), batch0.cuda(), ((round(6890*opt.slim), 3)  ), as_strings=True, print_per_layer_stat=False, verbose=True)
TypeError: get_model_complexity_info() got multiple values for argument 'print_per_layer_stat'`

I think there is something wrong with the input to get_model_complexity_info(). Do you know how to fix it?

**Comment by layumi** [comment]
Do you install the model complexity? 
Actually I have include the model complexity calculation in this repo. 
I am not sure whether it is due to the conflict between the repo one with the package one. 

Or you may skip the train_M.py, line 362. It does nothing with training, just for one quick reference.

**Comment by Zhangyongtao123** [comment]
> Do you install the model complexity? Actually I have include the model complexity calculation in this repo. I am not sure whether it is due to the conflict between the repo one with the package one.
> 
> Or you may skip the train_M.py, line 362. It does nothing with training, just for one quick reference.

Skipping it is fine. Thanks for your reply.
