### ISSUE TITLE
how to set 8192 points for each human body?

### ISSUE THREAD

**Issue by changshuowang** [layumi/person-reid-3d#17]
Hello, Dr. Zheng. Thank you very much for your excellent work. I want to know how to set 8192 points for each human body? Where can this part of the code be found in the HMR project? Thank you very much for your reply.

**Comment by layumi** [comment]
Thanks for your attention on our project. 
8192 is defined in the smpl body model. It is a morphable body model. 
You can find the npy file at https://github.com/layumi/hmr/tree/master/src/tf_smpl.

**Comment by changshuowang** [comment]
OK. Thank you, Dr. Zhang.
