### ISSUE TITLE
Lack of ./snapshot

### ISSUE THREAD

**Issue by z915287285** [layumi/person-reid-3d#18]
大神你好，最近在拜读您的文章，想结合Demo理解，但根据您的readme.md，有一个已经训练好的model，但是在repo中，并没有发现？

**Comment by layumi** [comment]
你好 @z915287285 
因为模型我都重新训练了，所以把老的去掉了。
最近的新模型都传上来了，你可以看看。大感谢！

**Comment by z915287285** [comment]
非常感谢大佬，这边已经看见您的新模型。非常感谢！
