### ISSUE TITLE
Problem with swa_utils

### ISSUE THREAD

**Issue by akartsight** [layumi/person-reid-3d#6]
Hi. Can you help please. I can not figure out this error. I use pytorch=1.4.0 torchvision=0.5.0 cudatoolkit=10.1 
![656565](https://user-images.githubusercontent.com/74756746/103049790-eb5f6d80-45bc-11eb-9b06-63351d0fbec3.png)

**Comment by layumi** [comment]
Thanks @akartsight 
It is my mistake. 
swa_utils is used in the latest pytorch. I just involve it in the repo at 
https://github.com/layumi/person-reid-3d/blob/master/swa_utils.py

**Comment by akartsight** [comment]
> Thanks @akartsight
> It is my mistake.
> swa_utils is used in the latest pytorch. I just involve it in the repo at
> https://github.com/layumi/person-reid-3d/blob/master/swa_utils.py

Thanks, it works. But could you tell me about the dataset (Market (2D + 3D)) I downloaded it in order to skip the preparation step. Now I can't figure out what path it should have in order to start training.

**Comment by layumi** [comment]
Just put the datasets in the same folder of the code.
```
├── 2DMarket\
│   ├── query/  
│   ├── train_all/
│   ├── ...
├── 3DMarket+bg\
│   ├── query/  
│   ├── train_all/
│   ├── ...
├── train.py
├── test.py 
├── ...
```

**Comment by akartsight** [comment]
> Just put the datasets in the same folder of the code.
> 
> ```
> ├── 2DMarket\
> │   ├── query/  
> │   ├── train_all/
> │   ├── ...
> ├── 3DMarket+bg\
> │   ├── query/  
> │   ├── train_all/
> │   ├── ...
> ├── train.py
> ├── test.py 
> ├── ...
> ```

What about this? Thanks for your help
![1111111](https://user-images.githubusercontent.com/74756746/103057614-32a02b00-45ca-11eb-89f4-f5802c824b53.png)

**Comment by akartsight** [comment]
> Just put the datasets in the same folder of the code.
> 
> ```
> ├── 2DMarket\
> │   ├── query/  
> │   ├── train_all/
> │   ├── ...
> ├── 3DMarket+bg\
> │   ├── query/  
> │   ├── train_all/
> │   ├── ...
> ├── train.py
> ├── test.py 
> ├── ...
> ```

Hello again. I managed to run the code. Could you explain what it means. Rank@1: 0.794537 Rank @ 5: 0.921318 Rank @ 10: 0.949822 mAP: 0.580073. And how to use my pictures
